# -*- coding: utf-8 -*-
"""Eye.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6JzZLrwHNAjqko4nn9syJQo6K_irqrP
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier, BaggingClassifier, ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression, RidgeClassifier, Perceptron, SGDClassifier
from sklearn.naive_bayes import GaussianNB, BernoulliNB
from sklearn.svm import SVC, NuSVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score,roc_curve,auc

from google.colab import drive
drive.mount('/content/drive')

file_path = "/content/drive/My Drive/Colab Notebook Data/Dry_Eye_Dataset.csv"

data = pd.read_csv(file_path)

import numpy as np
from sklearn.preprocessing import LabelEncoder

# Identify object columns
object_cols = data.select_dtypes(include="object").columns

# Process each object column
for col in object_cols:
    if data[col].isin(['Y', 'N']).all():
        # Encode 'Y'/'N' columns to 1/0
        data[col] = data[col].replace({"Y": 1, "N": 0})
    elif col == "Gender":
        # Encode 'Gender' 'F'/'M' to 1/0
        data[col] = data[col].replace({"F": 1, "M": 0})
    elif col == "Blood pressure":
        # Encode 'Blood pressure' using LabelEncoder
        le = LabelEncoder()
        data[col] = le.fit_transform(data[col])
    else:
        # For any other remaining object columns, use LabelEncoder as a general solution
        # This ensures all object columns are handled numerically
        le = LabelEncoder()
        data[col] = le.fit_transform(data[col])

# Verify changes
data.info()

data.head(5)

data.info()

numerical_col=data.select_dtypes(include="number")
for col in numerical_col.columns:
    plt.figure(figsize=(8,3))
    sns.histplot(data=numerical_col[col],kde=True,bins=30)
    plt.title(f"Histogram of {col}")
    plt.show()

plt.figure(figsize=(6, 5 * len(numerical_col.columns)))
for i, col in enumerate(numerical_col.columns, 1):
    plt.subplot(len(numerical_col.columns), 1, i)
    sns.boxplot(data=numerical_col[col])
    plt.title(f"Boxplot for {col}")

plt.tight_layout()
plt.show()

"""##Data Preprocessing"""

data.drop_duplicates(inplace=True)

data.shape

#check null value

print(data.shape,"\n\n\n\n",data.isnull().sum())

missing_values = data.isna().sum()
missing_values_df = pd.DataFrame(missing_values[missing_values > 0]) # Filter to show only columns with missing values
missing_values_df = missing_values_df.reset_index()
missing_values_df.columns = ['Column Names', 'Missing_Values']

if not missing_values_df.empty:
    plt.figure(figsize = (14, 10))
    sns.barplot(x = "Column Names", y = "Missing_Values", data = missing_values_df, palette = "Spectral")
    plt.title("Missing Values", fontsize = 18, weight = "bold")
    plt.ylabel('Count', fontsize=14)
    plt.xticks(rotation=45, fontsize = 14)
    plt.show()
else:
    print("No missing values found in the dataset.")

#check that if i remove all null value what happend

# Assuming your DataFrame is named 'data'
df_cleaned = data.dropna()

# Check the result
print(df_cleaned.shape,'\n\n',df_cleaned.isnull().sum())

# So we can not remove row. Because the data size is reduced huge

# Now we replace missing values with the same age value within each group


# Assuming your DataFrame is named 'df'

# for group in df['group'].unique():
#     df.loc[df['group'] == group, :] = df.loc[df['group'] == group, :].fillna(method='ffill')

# print(df.shape, '\n\n', df.isnull().sum())

# Since previous checks confirmed no missing values, this step is not needed.

# Based on previous checks, there are no missing values, so this step is not needed.

# Assuming your DataFrame is named 'data'
df_cleaned = data.dropna()

# Check the result
print(df_cleaned.shape, '\n\n', df_cleaned.isnull().sum())

"""##Outlier Checking"""

import seaborn as sns
import matplotlib.pyplot as plt

# Assuming 'data' is your DataFrame

# Create box plots for numerical columns
plt.figure(figsize=(40, 6))
sns.boxplot(data=data)
plt.xticks(rotation=45)
plt.show()

data.columns

"""##Outlier Remove"""

data.info()

df_numeric = data.select_dtypes(include=np.number)

df_numeric.head()

# calculating zscore of numeric columns in the dataset
from scipy import stats
z = np.abs(stats.zscore(df_numeric))
print(z)

# Defining threshold for filtering outliers
threshold = 3
print(np.where(z >= 3))

data.shape

#filtering outliers retaining only those data points which are below threshhold
df_numeric = df_numeric[(z <= 3).all(axis=1)]

df_numeric.shape

fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, sharey=False, figsize=(14,6))

# Assuming 'Dry Eye Disease' is the target column in 'data'
target_column = 'Dry Eye Disease'

# Pie chart
ax1 = data[target_column].value_counts().plot.pie(
    autopct="%1.0f%%",
    labels=["No Dry Eye Disease (0)", "Dry Eye Disease (1)"], # Assuming 0 and 1 are the labels
    startangle=60,
    ax=ax1
)
ax1.set(title=f'Percentage of {target_column} in Dataset')
ax1.set_ylabel('') # Remove y-label for pie chart for cleaner look

# Bar chart
ax2 = data[target_column].value_counts().plot(kind="barh", ax=ax2)
for i,j in enumerate(data[target_column].value_counts().values):
    ax2.text(.5, i, j, fontsize=12)
ax2.set(title=f'No. of {target_column} in Dataset')

plt.tight_layout()
plt.show()

# X = all columns except outcome
# y = outcome

y = data[['Dry Eye Disease']]
X = data.drop(columns = ['Dry Eye Disease'])

"""##Oversampling using SMOTE"""

import pandas as pd
from imblearn.over_sampling import SMOTE

# Re-define X and y from the 'data' DataFrame after all categorical columns have been encoded.
# This ensures X and y contain only numerical values as required by SMOTE.
y = data[['Dry Eye Disease']]
X = data.drop(columns=['Dry Eye Disease'])

smote = SMOTE(sampling_strategy='minority')
X_resampled, y_resampled = smote.fit_resample(X, y)

X_resampled.shape, y_resampled.shape

y_resampled.value_counts()

fig, (ax1, ax2) = plt.subplots(nrows=1, ncols=2, sharey=False, figsize=(14,6))

target_column_name = 'Dry Eye Disease'

ax1 = y_resampled[target_column_name].value_counts().plot.pie(
                   autopct = "%1.0f%%",
                   labels=["No Dry Eye Disease (0)","Dry Eye Disease (1)"],
                   startangle = 60,
                   ax=ax1);
ax1.set(title = f'Percentage of {target_column_name} in Dataset')
ax1.set_ylabel('') # Remove y-label for pie chart for cleaner look

ax2 = y_resampled[target_column_name].value_counts().plot(kind="barh" ,ax =ax2)
for i,j in enumerate(y_resampled[target_column_name].value_counts().values):
    ax2.text(.5,i,j,fontsize=12)
ax2.set(title = f'No. of {target_column_name} in Dataset')
plt.show()

y = y_resampled.rename(columns={'Dry Eye Disease': 'outcome'})
X = X_resampled

from sklearn.impute import KNNImputer
# imputerX = SimpleImputer(missing_values=np.nan, strategy='mean')
imputerX = KNNImputer(missing_values=np.nan, n_neighbors = 5)
cols = X.select_dtypes(include='float64').columns

len(cols),cols #36 column

imputerX.fit(X[cols])

X[cols] = imputerX.transform(X[cols])
X.info()

# This cell is no longer needed as y is already processed as a clean DataFrame
# from sklearn.impute import SimpleImputer
# # Imputing y with most frequent value
# imputer_y = SimpleImputer(strategy = "most_frequent")
# imputer_y.fit(y_resampled)
# y = imputer_y.transform(y_resampled)
# y

# This cell is no longer needed as y is already processed as a clean DataFrame
# y = pd.DataFrame(y, columns=['outcome'], dtype='int64')

df_final = X_resampled.copy()
df_final['outcome'] = y['outcome']
df_final.head()

df_final.shape

# Changing gendera to gender
df_final.rename(columns = {
    'gendera':'gender',
    'Hyperlipemia':'hyperlipidemia'
},
          inplace = True)

df_final.columns

"""##Feature Engineering

"""

# This cell's content has been moved to an earlier point in the notebook to ensure timely feature engineering.

# This cell is now redundant as Gender encoding is handled in kPc9kNv1imh5

# This cell is now redundant as Blood pressure encoding is handled in kPc9kNv1imh5

data.info()

plt.figure(figsize=(12,7))
sns.heatmap(data.corr())

data.corr()

data.head(5)

x=data.drop(["Dry Eye Disease"],axis=1)
y=data["Dry Eye Disease"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

"""##Classifiers

"""

models = {
    "Random Forest Classifier": RandomForestClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "AdaBoost Classifier": AdaBoostClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    "Bagging Classifier": BaggingClassifier(),
    "Extra Trees Classifier": ExtraTreesClassifier(),
    "Logistic Regression": LogisticRegression(),
    "Ridge Classifier": RidgeClassifier(),
    "Perceptron": Perceptron(),
    "SGD Classifier": SGDClassifier(),
    "Gaussian Naive Bayes": GaussianNB(),
    "Bernoulli Naive Bayes": BernoulliNB(),
    "Support Vector Classifier (SVC)": SVC(),
    "Nu-Support Vector Classifier": NuSVC(),
    "Linear SVC": LinearSVC(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Linear Discriminant Analysis": LinearDiscriminantAnalysis(),
    "Quadratic Discriminant Analysis": QuadraticDiscriminantAnalysis()
}

"""##Results"""

metrics = {
    'Model': [],
    'Accuracy': [],
    'Precision': [],
    'Recall':[]
}
for name,model in models.items():
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    recall=recall_score(y_test,y_pred)
    precision=precision_score(y_test,y_pred)
    metrics['Model'].append(name)
    metrics['Accuracy'].append(acc * 100)
    metrics['Precision'].append(precision * 100)
    metrics['Recall'].append(recall * 100)
    print(f"Model: {name}")
    print(f"Accuracy: {acc*100}")
    print(f"Precision: {precision*100}")
    print(f"Recall: {recall*100}")
    print(f"Recall: {f1*100}")
    print("-" * 30)

metrics_df = pd.DataFrame(metrics)
print("\n--- Model Performance Summary ---")
print(metrics_df.sort_values(by='Accuracy', ascending=False))

"""##Prediction with the Best Model"""

# Select the best performing model (e.g., Support Vector Classifier)
best_model = models['Support Vector Classifier (SVC)']

# Choose a sample from the test set for prediction
# For demonstration, let's pick the first sample from x_test
sample_to_predict = x_test[0].reshape(1, -1) # Reshape for single sample prediction

# Make the prediction
prediction = best_model.predict(sample_to_predict)

# Interpret the prediction
if prediction[0] == 0:
    print("The model predicts: No Dry Eye Disease")
else:
    print("The model predicts: Dry Eye Disease")